source:         .
destination:    /var/www/jameswolff/
includes_dir:   ./_includes
url:		https://jameswolff.me

gems: ["jekyll-paginate", "gemoji"]

include:        [".htaccess"]
exclude:        ["build.sh", "README.md"]
keep_files:     [".git"]
encoding:       "utf-8"
markdown_ext:   "markdown,md"

paginate: 5
paginate_path: "/page:num/"

future:         true
unpublished:    false

incremental:    false

excerpt_separator: <!--more-->

markdown:       kramdown
highlighter:    rouge

permalink:      /:year/:month/:day/:title
paginate_path:  /page:num
timezone:       America/Chicago

emoji_dir: /media/emoji

kramdown:
    input:              GFM
    auto_ids:           true
    footnote_nr:        1
    parse_block_html:   true
    entity_output:      as_char
    toc_levels:         1..6
    smart_quotes:       lsquo,rsquo,ldquo,rdquo
